arkemishub/arke-server

- lib/arke_server/controllers/arke_controller.ex
- lib/arke_server/controllers/group_controller.ex
- lib/arke_server/controllers/struct_controller.ex
- lib/arke_server/controllers/topology_controller.ex
- lib/arke_server/controllers/unit_controller.ex
- lib/arke_server/router.ex
- mix.exs
fix: get group/parameter/[:unit and :arke]
> fix: get unit plug

- lib/arke_server/controllers/topology_controller.ex
- test/controllers/arke_controller_test.exs
- test/controllers/group_controller_test.exs
> fix: remove configuration in favor of metadata

- lib/arke_server/plugs/build_filters.ex
> fix: build_filters condition is now called with Parameter instead of id

- lib/arke_server/router.ex
> fix: parameterController now use the ParameterController module

- lib/arke_server/controllers/auth_controller.ex
- lib/arke_server/router.ex
> fix: add change_password auth endpoint

- lib/arke_server/plugs/build_filters.ex
> fix: return 400 if no operator or logic has been found

- lib/arke_server/plugs/build_filters.ex
> fix: build in filters from query params

- lib/arke_server/plugs/build_filters.ex
- test/controllers/unit_controller_test.exs
- test/support/create_arke.ex
> feat: add isnull filter operator

- lib/arke_server/controllers/auth_controller.ex
> fix: reset password token creation

- lib/arke_server/controllers/arke_controller.ex
> fix: add status to arke_controller call_function

- lib/arke_server/controllers/unit_controller.ex
> fix: add runtime data to unit controller update

- lib/arke_server/controllers/auth_controller.ex
Fix typo `default` on AUTH_MODE
> fix: typo default on AUTH_MODE

- lib/arke_server/controllers/auth_controller.ex
Add `APP_REVIEW_EMAIL` and `APP_REVIEW_CODE` env variable that define which email (separated with comma) will receive a specific test code (default: 1234)
> chore: review email for tester OTP signin

- lib/arke_server/controllers/topology_controller.ex
- lib/arke_server/plugs/build_filters.ex
- lib/arke_server/utils/query_filters.ex
- mix.exs
> chore: better error handling in query_filter

- lib/arke_server/controllers/topology_controller.ex
- lib/arke_server/router.ex
> feat: add update link route and method

- lib/arke_server/utils/query_filters.ex
> fix: parenthesis query

- lib/arke_server/controllers/arke_controller.ex
- lib/arke_server/utils/query_filters.ex
Please include a summary of the change and which issue is fixed.
Please also include relevant motivation and context.
Fixes # (issue)
> feat: handled child_only_permission

- lib/arke_server/controllers/group_controller.ex
- lib/arke_server/plugs/permission.ex
- lib/arke_server/router.ex
> feat: group custom fn

- lib/arke_server/controllers/arke_controller.ex
- lib/arke_server/controllers/group_controller.ex
same as https://github.com/arkemishub/arke-server/commit/2178035d7fe6e9058aef084788584f6cbbef1eeb
> fix: handle file response type in custom fns

- lib/arke_server/controllers/auth_controller.ex
- lib/arke_server/plugs/permission.ex
- remove permission check on lib/auth/change_password
- remove otp check in change_password
> fix: change pwd permission plug

- lib/arke_server/controllers/auth_controller.ex
- lib/arke_server/controllers/oauth_controller.ex
> fix: oauth signin and signup email

- lib/arke_server/controllers/oauth_controller.ex
> fix: update member login time

- lib/arke_server/controllers/auth_controller.ex
- lib/arke_server/utils/onesignal.ex
> chore: align dev

- lib/arke_server/controllers/auth_controller.ex
- lib/arke_server/email_manager/mailer.ex
- lib/arke_server/message_manager/sms_manager.ex
first part of backport (mailer_module) taken auth_controller.ex modify from: https://github.com/arkemishub/arke-server/pull/46
second part of backport (otp via sms) taken from: https://github.com/arkemishub/arke-server/pull/61
To review mix.lock before merge
> feat: [backport] add mailer_module and sms otp

- lib/arke_server/controllers/auth_controller.ex
> feat: add otp management via sms

- lib/arke_server/controllers/oauth_controller.ex
do not update access time if member does not exists
> fix: oauth login update access time

- lib/arke_server/controllers/auth_controller.ex
> fix: hide phone number empty string

- lib/arke_server/oauth/providers/microsoft.ex
> feat: add microsoft provider for oauth

- lib/arke_server/controllers/auth_controller.ex
> fix: add param last_access_time on signup

- lib/arke_server/controllers/arke_controller.ex
- lib/arke_server/controllers/unit_controller.ex
- lib/arke_server/utils/bulk.ex
> fix: bulk return units

- lib/arke_server/controllers/auth_controller.ex
as per title
depends on: https://github.com/arkemishub/arke-auth/pull/19
> feat: add signin via arke temporary_token

- lib/arke_server/utils/query_filters.ex
- lib/arke_server/utils/query_order.ex
Forward filter `path` to `QueryManager.condition`
> feat: add nested filters and sort

- lib/arke_server/controllers/arke_dev_function_controller.ex
- lib/arke_server/controllers/backoffice_controller.ex
- lib/arke_server/router.ex
add endpoint to get db structure like export_data only for superadmin
> feat: export_data endpoint

- lib/arke_server/controllers/unit_controller.ex
> fix: add runtime_data conn in unit update

- lib/arke_server/email_manager/mailer.ex
> feat: add cc to email base mailer struct

- lib/arke_server/controllers/arke_controller.ex
- lib/arke_server/controllers/arke_dev_function_controller.ex
- lib/arke_server/controllers/auth_controller.ex
- lib/arke_server/controllers/group_controller.ex
- lib/arke_server/plugs/auth_pipeline.ex
- lib/arke_server/plugs/get_unit.ex
- lib/arke_server/plugs/permission.ex
Depends on https://github.com/arkemishub/arke-auth/pull/22
> feat: implemented new permission check for impersonate, added auth pipeline for impersonate

- .github/workflows/publish_hex.yml
> fix: gh action
